[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpg" # jpg files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.png" # png files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
